### ISSUE TITLE
Can't join groups in Empathy (No Such Method [...]Adaptee::groupFlagsChanged)

### ISSUE THREAD

**Issue by criztovyl** [TelepathyQt/telepathy-morse#12]
```
QMetaObject::invokeMethod: No such method Tp::BaseChannelGroupInterface::Adaptee::groupFlagsChanged(Tp::ChannelGroupFlags,Tp::ChannelGroupFlags)
Candidates are:
groupFlagsChanged(uint,uint)
```

Compiled morse and TelepathyQt from Git.
Debin Stretch, Empathy 3.12.11

**Comment by Kaffeine** [comment]
You're right.
It is a bug in TpQt. I'm not sure if this would fix groups for Empathy btw, going to test it.

**Comment by Kaffeine** [comment]
Found the real issue. Morse one at this time.

**Comment by criztovyl** [comment]
Sry, "Morse one at this time."? ^^

**Comment by Kaffeine** [comment]
I just fixed crash (real issue) by commit TelepathyQt/telepathy-qt@2f91be510529308c5ca08b479566fa4ca0212dde.
The signal emission fixed in TelepathyQt/telepathy-qt@7895cca53a868836bdc87ac3cd533e744c373931.

It seems that there is also one issue, finally in Morse — self contact is not listed in group chat contacts.
I'll try to fix it tomorrow.

Thanks for the report! :)

**Comment by criztovyl** [comment]
Hey,
what is the best way to reinstall telepathy-qt and morse?
I pulled both again (morse didn't changed^^), build and installed. But
the problem persists.
If I understand you right, your commits should resolve this, so what
happend?
Thanks.
Am Freitag, den 04.12.2015, 11:41 -0800 schrieb Alexandr Akulich:

> Closed #12.
> —
> 
> ## Reply to this email directly or view it on GitHub.
> 
> Visit me:
> http://joinout.de
> http://criztovyl.joinout.de
> https://github.com/criztovyl

**Comment by Kaffeine** [comment]
Morse statically links to TelepathyQt-Service. This means that the library, available at compile-time would be built-in into the morse executable.
In order to use new TelepathyQt, you need to reinstall TelepathyQt and then rebuild all qt-based connection manager.
The thing is that we have no stable API for ConnectionManagers, so we don't promise any compatibility yet. That's why the only reliable way to make old qt-based CMs to work after TpQt update is to built-in unstable part into CM.
This is gonna be changed/fixed in some future, so CM would gain all fixes and improvements of new TpQt without rebuild.

**Comment by criztovyl** [comment]
So, what do I have to rebuild?
I rebuild TpQt, but what are "all qt-based connection manager"?

**Comment by criztovyl** [comment]
I now also rebuild TelegramQt (not Telepathy^^) and  now, afer rebooting my computer (because I also installed graphics card firmware btw), I can join groups. Maybe because Empathy stays running all the time?
And I can see myself in group list :) (But I'm offline?)
![morse](https://cloud.githubusercontent.com/assets/2174918/11607003/4f34b0d6-9b36-11e5-8821-cabd1bf813b1.png)

**Comment by Kaffeine** [comment]
You needed to 1) Rebuild TelepathyQt, 2) Rebuild Morse after that, 3) Restart Morse.
You can use `killall telepathy-morse` to restart Morse invoked automatically.

**Comment by criztovyl** [comment]
Thx.
